name: Setup env
description: Setup python, poetry and install deps

inputs:
  python:
    description: 'Python toolchain to use'

runs:
  using: composite
  steps:
    - name: Infer python version
      run: |
        echo Python version...
        if [[ -z "${{ inputs.python }}" ]]
        then
            cat .python-version
            echo "PYTHON=$(cat .python-version)" >> "$GITHUB_ENV"
        else
            echo "${{ inputs.python }}"
            echo "PYTHON=${{ inputs.python }}" >> "$GITHUB_ENV"
        fi
      shell: bash
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v4
      with:
        enable-cache: true
        cache-prefix: ${{ env.PYTHON }}
    - name: Rye sync
      if: "${{ inputs.python != '' }}"
      run: rye pin ${{ inputs.python }}
      shell: bash
    - name: Rye sync
      run: rye sync --no-lock
      shell: bash
