name: Setup env
description: Setup python, poetry and install deps

inputs:
  python:
    description: 'Python toolchain to use'

runs:
  using: composite
  steps:
    - name: Infer python version
      run: |
        echo Python version...
        if [[ -z "${{ inputs.python }}" ]]
        then
            cat .python-version
            echo "PYTHON=$(cat .python-version)" >> "$GITHUB_ENV"
        else
            echo "${{ inputs.python }}"
            echo "PYTHON=${{ inputs.python }}" >> "$GITHUB_ENV"
        fi
      shell: bash
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
    - name: install python
      run: uv python install ${{ inputs.python }}
      shell: bash
    - name: pin python
      run: uv python pin ${{ inputs.python }}
      shell: bash
    - name: uv sync
      run: uv sync --locked
      shell: bash
