name: Setup env
description: Setup python, poetry and install deps

inputs:
  python:
    description: 'Python toolchain to use'

runs:
  using: composite
  steps:
    - name: Install the latest version of rye
      uses: eifinger/setup-rye@v3
      with:
        enable-cache: true
        cache-prefix: ${{ inputs.python }}
    - name: Rye sync
      if: "${{ inputs.python != '' }}"
      run: rye pin ${{ inputs.python }}
      shell: bash
    - name: Rye sync
      run: rye sync --no-lock
      shell: bash
