[tool.poetry]
name = "sanremo"
version = "0.1.0"
description = "cli to see if San Remo is interesting yet"
authors = ["Alexis Daboville"]
readme = "README.md"
packages = [{include = "sanremo", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
clint = "^0.5.1"
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies]
black = ">= 24.4.2"
isort = ">= 5.13.2"
pre-commit = ">= 3.7.1"
pytest = ">= 8.2.2"

[tool.poetry.scripts]
sanremo = "sanremo:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
