[tool.poetry]
name = "sanremo"
version = "0.1.0"
description = ""
authors = ["Alexis Daboville <alexis.daboville@gmail.com>"]
readme = "README.md"
packages = [{include = "sanremo", from = "src"}]

[tool.poetry.dependencies]
python = "^3.12"
requests = "^2.32.3"
clint = "^0.5.1"

[tool.poetry.group.dev.dependencies]
black = "^24.4.2"
pytest = "^8.2.2"

[tool.poetry.scripts]
sanremo = "sanremo:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
