name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup env
        uses: ./.github/actions/setup
      - name: Run tests
        run: rye test -- -v --junitxml=junit/test-results.xml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: pytest results
          path: junit/*.xml
          reporter: java-junit

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup env
        uses: ./.github/actions/setup
      - name: Run tests
        run: rye lint

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup env
        uses: ./.github/actions/setup
      - name: Run tests
        run: rye fmt --check
