name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11", "3.12", "3.13"]
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup env
        uses: ./.github/actions/setup
        with:
          python: ${{ matrix.python }}
      - name: Run tests
        run: uv run pytest -v --junitxml=junit/test-results.xml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: "pytest results (${{ matrix.python }})"
          path: junit/*.xml
          reporter: java-junit

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup env
        uses: ./.github/actions/setup
      - name: ruff check
        run: uv run ruff check

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup env
        uses: ./.github/actions/setup
      - name: ruff format
        run: uv run ruff format --check
