name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Setup env
        uses: ./.github/actions/setup
      - name: Run tests
        run: poetry run pytest -v --junitxml=junit/test-results.xml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: pytest results
          path: junit/*.xml
          reporter: java-junit

  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src ./tests"

  isort:
    runs-on: ubuntu-latest
    steps:
      - name: Setup env
        uses: ./.github/actions/setup
      - uses: isort/isort-action@master
        with:
          sortPaths:
            - src
            - tests
